expression = (type:`invoke` val:proc_invoke_expr)
           | (type:`procedure` val:procedure_expr)
           | (type:`operator` val:expression_operator)
           | (type:`identifier` val:IDENTIFIER);
