operator = statement_operator | expression_operator;

statement_operator
= (@:`s_assign` @:op_s_assign)
| (@:`setattr` @:op_s_setattr)
| (@:`setitem` @:op_s_setitem)

| (@:`del` @:op_s_del)
| (@:`delattr` @:op_s_delattr)
| (@:`delitem` @:op_s_delitem)
;

expression_operator
= (@:`ternary` @:op_ternary)
#TODO:slicing
# asymmetrical operators
| (@:`pos` @:op_e_pos)
| (@:`neg` @:op_e_neg)
| (@:`inv` @:op_e_inv)
| (@:`not` @:op_e_not)
# symmetrical operators
| (@:`e_assign` @:op_e_assign)
| (@:`getattr`  @:op_e_getattr)
| (@:`getitem`  @:op_e_getitem)
| (@:`contains` @:op_e_contains)
## misc operators (usually symbols)
| (@:`at` @:op_e_at)
### arithmetic
| (@:`add`  @:op_e_add)
| (@:`sub`  @:op_e_sub)
| (@:`mult` @:op_e_mult)
| (@:`div`  @:op_e_div)
| (@:`exp`  @:op_e_exp)
| (@:`mod`  @:op_e_mod)
### bitwise
| (@:`lshift` @:op_e_lshift)
| (@:`rshift` @:op_e_rshift)
| (@:`band`   @:op_e_bitand)
| (@:`bor`    @:op_e_bitor)
| (@:`bxor`   @:op_e_bitxor)
### logical
| (@:`land` @:op_e_logand)
| (@:`lor`  @:op_e_logor)
| (@:`lxor` @:op_e_logxor)
### comparison
| (@:`eq` @:op_e_eq)
| (@:`lt` @:op_e_lt)
| (@:`le` @:op_e_le)
| (@:`gt` @:op_e_gt)
| (@:`ge` @:op_e_ge)
;
