procedure_stmt = rtype:IDENTIFIER bind:identifier "(" [args:argdeflist [","]] ")" body:block;
procedure_expr = rtype:IDENTIFIER "(" [args:argdeflist [","]] ")" body:block;

argdeflist = ",".{ argdef }*; # val:`None` mark:`pos` "/") | (val:`None` mark:`kw` "*") | (val:argdef mark:`None`) }*;
argdef = ["*" var:`args` ["*" var:`kwargs`]] name:identifier ":" type:identifier ["=" default:expression];

proc_invoke_expr = name:IDENTIFIER "(" [args:arglist [","]] ")";
arglist = ",".{ arg };
arg = ([name:identifier "="] val:expression) | ("*" var:`args` ["*" var:`kwargs`] val:expression);
